import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Crypto login",
  description: "Generated by create next app",
};
export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {" "}
      login layout
      {children}
    </div>
  );
}
